// Builds a SoapUI project file (demo/prototype use, synthetic data only).

function escapeXml(v: string) {
  return v
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function cdata(v: string) {
  return `<![CDATA[${v.replace(/\]\]>/g, "]]]]><![CDATA[>")}]]>`;
}

export interface SoapUiRequest {
  name: string;
  body: string;
}

export interface SoapUiProjectOptions {
  projectName: string;
  interfaceName?: string;
  endpoint?: string;
  soapAction?: string;
  soap?: boolean;
  requests: SoapUiRequest[];
}

/** Splits generated output into individual documents when several samples were produced. */
export function splitSamples(output: string): string[] {
  const parts = output
    .split(/<!--\s*=+\s*Sample\s+\d+\s+of\s+\d+\s*=+\s*-->/g)
    .map((p) => p.trim())
    .filter(Boolean);
  return parts.length ? parts : [output.trim()];
}

export function buildSoapUiProject(options: SoapUiProjectOptions): string {
  const {
    projectName,
    interfaceName = `${projectName}-interface`,
    endpoint = "http://localhost:8080/mock",
    soapAction = "",
    soap = true,
    requests,
  } = options;

  const items = requests
    .map((req, i) => {
      const name = escapeXml(req.name || `Request ${i + 1}`);
      if (soap) {
        return `      <con:operation name="${name}" isOneWay="false" action="${escapeXml(soapAction)}" type="Request-Response">
        <con:call name="${name}">
          <con:endpoint>${escapeXml(endpoint)}</con:endpoint>
          <con:request>${cdata(req.body)}</con:request>
        </con:call>
      </con:operation>`;
      }
      return `      <con:resource name="${name}" path="/">
        <con:method name="${name}" method="POST">
          <con:request name="${name}">
            <con:endpoint>${escapeXml(endpoint)}</con:endpoint>
            <con:request>${cdata(req.body)}</con:request>
          </con:request>
        </con:method>
      </con:resource>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Atlas - synthetic demo data, prototype use only -->
<con:soapui-project name="${escapeXml(projectName)}" activeEnvironment="Default"
  xmlns:con="http://eviware.com/soapui/config">
  <con:settings/>
  <con:interface xsi:type="con:${soap ? "WsdlInterface" : "RestService"}" name="${escapeXml(interfaceName)}"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <con:settings/>
    <con:endpoints>
      <con:endpoint>${escapeXml(endpoint)}</con:endpoint>
    </con:endpoints>
${items}
  </con:interface>
  <con:properties/>
</con:soapui-project>
`;
}
