/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as FolderRouteImport } from './routes/folder'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiAiTestdataRouteImport } from './routes/api/ai-testdata'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderRoute = FolderRouteImport.update({
  id: '/folder',
  path: '/folder',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestdataRoute = ApiAiTestdataRouteImport.update({
  id: '/api/ai-testdata',
  path: '/api/ai-testdata',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dependencies': typeof DependenciesRoute
  '/documentation': typeof DocumentationRoute
  '/folder': typeof FolderRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-testdata': typeof ApiAiTestdataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dependencies': typeof DependenciesRoute
  '/documentation': typeof DocumentationRoute
  '/folder': typeof FolderRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-testdata': typeof ApiAiTestdataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dependencies': typeof DependenciesRoute
  '/documentation': typeof DocumentationRoute
  '/folder': typeof FolderRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-testdata': typeof ApiAiTestdataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dependencies'
    | '/documentation'
    | '/folder'
    | '/generate'
    | '/import'
    | '/api/ai-chat'
    | '/api/ai-testdata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dependencies'
    | '/documentation'
    | '/folder'
    | '/generate'
    | '/import'
    | '/api/ai-chat'
    | '/api/ai-testdata'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dependencies'
    | '/documentation'
    | '/folder'
    | '/generate'
    | '/import'
    | '/api/ai-chat'
    | '/api/ai-testdata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DependenciesRoute: typeof DependenciesRoute
  DocumentationRoute: typeof DocumentationRoute
  FolderRoute: typeof FolderRoute
  GenerateRoute: typeof GenerateRoute
  ImportRoute: typeof ImportRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiTestdataRoute: typeof ApiAiTestdataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder': {
      id: '/folder'
      path: '/folder'
      fullPath: '/folder'
      preLoaderRoute: typeof FolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-testdata': {
      id: '/api/ai-testdata'
      path: '/api/ai-testdata'
      fullPath: '/api/ai-testdata'
      preLoaderRoute: typeof ApiAiTestdataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DependenciesRoute: DependenciesRoute,
  DocumentationRoute: DocumentationRoute,
  FolderRoute: FolderRoute,
  GenerateRoute: GenerateRoute,
  ImportRoute: ImportRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiTestdataRoute: ApiAiTestdataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
